[features]
seeds = false

[programs.localnet]
solana_twitter_react = "DQcqgGNmDmG95QD4mGgyWpX28uGEv3AQay9d2ZzJgPtY"
[programs.devnet]
solana_twitter_react = "DQcqgGNmDmG95QD4mGgyWpX28uGEv3AQay9d2ZzJgPtY"
[programs.mainnet]
solana_twitter_react = "DQcqgGNmDmG95QD4mGgyWpX28uGEv3AQay9d2ZzJgPtY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/dany/.config/solana/id.json"

[workspace]
types = "app/idl/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/idl && cp target/idl/solana_twitter_react.json app/idl/solana_twitter_react.json"
