[features]
seeds = false
[programs.localnet]
solana_twitter_react = "DQcqgGNmDmG95QD4mGgyWpX28uGEv3AQay9d2ZzJgPtY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dany/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
hello = "echo 'wor... no. gfy.'"
