import { Html, Head, Main, NextScript } from "next/document";

const MyDocument = () => (
  <Html lang="en-GB">
    <Head>
      {/* <title>Solana Twitter</title> */}
      <meta
        name="description"
        content="Generated by create next app"
        charSet="utf-8"
      />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <body>
      <Main />
      <NextScript />
    </body>
  </Html>
);

export default MyDocument;
